Buy Team 52135: Added option to disable auto focus on Accordion component.
jp-mfrm/mfcl pull request #151
Opened 2021-12-09 23:54 UTC by hahn208

2021-12-10 05:42 UTC, CarlosRangel17 requested changes
Can we make this update to our ADO component library to keep things synced up there?

2021-12-10 05:43 UTC, CarlosRangel17 commented
> Can we make this update to our ADO component library to keep things synced up there?

Also, let's be sure to update the package.json version, and update the change log file

2021-12-21 16:22 UTC, hahn208 reviewed
Updated the Changelog and Package. Also added changes that I pushed to the ADO MFCL.

2021-12-21 16:46 UTC, CarlosRangel17 commented on package.json
> +  "version": "4.0.2",
This should be 4.0.3 :)

2021-12-21 16:51 UTC, CarlosRangel17 commented on src/Stepper/Step.tsx
> +import React, {FunctionComponent, ReactNode, memo, KeyboardEvent} from 'react'
These formatting changes seem unnecessary... I think the convention for this project would be to keep these spaces. We might need to align our VS Code formatter settings for this project? Yet another tech debt item on my to do list. 

Sorry to be pedantic, but can we revert these formatting changes for now?

2021-12-21 17:26 UTC, CarlosRangel17 approved these changes

2021-12-22 22:59 UTC, hahn208 commented
Closing to reopen and hopefully Vercel will just work.

2021-12-23 17:25 UTC, merged